### ISSUE TITLE
Setter - Software Engineer - Toronto

### ISSUE THREAD

**Issue by didjeridou** [TechnologyMasters/jobs#168]
### Read about us on TechCrunch
Read about our last round of funding with some of the best investors/partners in the world: [https://techcrunch.com/2018/11/02/setter-home/](https://techcrunch.com/2018/11/02/setter-home/)

### Salary Expectation

- $75,000 - $110,000 CAD
- Full Time

### Benefits

- Health benefits: 80% medical coverage, $1,250 Health Spending Account, $250 lifestyle spending account, travel insurance
- Fully stocked kitchen: unlimited drinks and snacks
- New Macbook
- Tons of team activites, mini-pub in the office with soft drinks and beer on tap
- Yearly offsite retreat
- Brick and beam office near Queen and Dufferin

### Location

- Toronto, Ontario
- Candidate may work from home for a few days every month

## What You'll Do _(Job Description)_

We are looking for smart and ambitious software engineers to help us build out our vision for cities of the future. You will be responsible for executing on initiatives designed to move the needle on key business goals via innovative solutions and highly-scalable, performant code. You’ll partner with colleagues in design and product management to help in the development of a fast-growing product that is reshaping the way people interact with their urban environment. We’re a high impact team with an ambitious mission and are looking for high caliber people to join us!

- Be accountable for the delivery of engineering solutions across all layers of our tech stack - from implementing SQL optimizations one day, to contributing to the UX / UI of our React Native app another day. 
- Your preference is obviously taken into account, and the bulk of your work will reside in the “layer” that you prefer to work on most 
- Dive into technical discussions to help us decide how, and with which technologies, to solve complex problems. 
- Help make Setter a technology industry leader by upholding the highest standards for integrity and quality, while keeping pragmatism in mind.

## What You Need to Be Successful _(Skills)_

- You have a strong sense of ownership, and a curiosity to learn and understand how things work, even if they take you outside your area of expertise. 
- You care about agile software processes, data-driven development, reliability, and disciplined experimentation. 
- You focus on customer happiness and see technologies (whether programming languages, frameworks, databases, etc.) as a means to an end. 
- You have strong communication skills, both spoken and written — a history of blogging or essay-writing is helpful. 
- Experienced in building and maintaining complex software systems. 
- A team player who looks out for the group’s best interest, and keeps their ego in check.

### Must Have

- Experience working with JavaScript in a non-trivial context. 
- Software experience and/or BS/MS degree in Computer Science 
- Ability to relocate to Toronto, Canada. 
- 2+ years working experience.

### Nice to Have

- Experience with NodeJS 
- Experience with TypeScript 
- Experience with Rust 
- Experience with GraphQL

## About Our company

We are on a mission to create a home maintenance service so simple to use that homeowners can just forget about it. We've built an exceptional team and have raised money from top-notch investors to make our vision a reality for homeowners of the world. The opportunity to take on a big role and have huge impact is very real. Our culture is collaborative, focused, and transparent.

## How to apply

Apply using the link below and write "Technology Masters Github" in the "Additional Information" box at the bottom: [https://jobs.lever.co/setter/2bff1cbc-09d6-4a92-9ec4-c26bf95d67e5](https://jobs.lever.co/setter/2bff1cbc-09d6-4a92-9ec4-c26bf95d67e5)

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [ ] Remote Regional
- [ ] Remote OK

**Comment by gDelgado14** [comment]
I want to preface this comment by saying that I work here, and thus I have quite a bias ... But with that said, I do want to give a huge shoutout to the company. Setter has a thriving engineering culture that emphasizes creativity, critical thinking, and independent thought.

# Examples:

## Rust

We went with rust after a long discussion around options for improving developer experience, runtime guarantees (At the time, we were running 100% on TypeScript, and because the ecosystem is littered with `any`s and outdated types, runtime errors are still quite common), and future-proofing our system for high-throughput and scaleability.

For big (irreversible or nearly irreversible) decisions, we enforce a RFC (request for comment) process. Where one engineer gets assigned the responsibility of proposing something and the rest of the team critiques the proposal on its objective merits.

After lots of back and forth, we agreed that Rust was indeed a good option. And we implemented a tiny module running in the same vm as node through FFI.

Fast forward 6 months later and we are slowly replacing Node / TypeScript code with Rust code. Even the skeptics on the team are now really loving Rust.

Another example of our team assessing tools on their merits is with GraphQL: The popularity of GraphQL has exploded in recent time. And conversations around it always pop up. But when we judge it on its merits, it just doesn't make sense for our team.

## Freedom To Openly Object

During sprint planning meetings we get shown the set of upcoming work. Sometimes some of that work requests we implement feature "X". Part of our process is to have an open dialogue around the core problem a feature is trying to address and assess whether that requested feature even makes sense. Oftentimes our awesome product manager will agree that our counterpoints are valid. And she'll readjust the work to address the issues we brought up.

I've heard horror stories where the engineering team is just seen as a tool to build "X", only for management to realize 6, 7, 8 or more months down the road that the engineers did have valid concerns. I really value how much we are heard and listened to in the organization.

Obviously the freedom goes both ways :) We get critiqued on our proposed solutions all the time, and we appreciate the feedback and work to address the concerns of the business.
