### ISSUE TITLE
Senior Typescript Engineer

### ISSUE THREAD

**Issue by ma2780** [TechnologyMasters/jobs#530]
Forward - Senior Typescript Engineer - Remote

- Contract / Full Time
- Remote

Hey everyone! Looking for a Senior Typescript Engineer to help out the CTO at a small seed stage company. The role is remote and the contract would last 3-6 months. You can read a bit more about the role here: https://work.forward.id/typescript-engineer

Ideally you have:

- React / Redux experience
- Experience working at early stage startups
- Typescript experience
- Experience building APIs 
- Experience writing server side javascript/typescript 
- Experience consulting 
- 8+ years experience 

If you’re interested, please feel free to DM me with your resume. Thanks!

- [ ] Full Time
- [ ] Part Time
- [x] Contract
- [ ] Internship
- [ ] Remote Worldwide
- [x] Remote Regional
- [ ] Remote OK

**Comment by SeniorITNinja** [comment]
Hello, Nice to meet you.
After graduating with my Bachelor’s degree in Computer Science, I’ve spent the last 6+ years building professional experience as a Software Development.
I am very interested in this position because my skillsets match & experience as your company looking for.
my review: Passionate & Responsible developer, Best Colleague.
I’m ready to bring my skills to this developing marketplace. I’ve always dreamed of working at this company, and I was excited to see an opening that’s a perfect fit for my experience and abilities.
Have an extremely software developing, engineering's versatile skill set and I understand the importance of being interactive and enjoy communicating with others for the benefit of the company and
I can be reached anytime by skype(live:.cid.b1a38583392e35b0 ), email ( futuresea.dev@gmail.com ).
I look forward to speaking with you soon.
Sincerely,
