### ISSUE TITLE
Apex Labs - Python/Django Engineer - Remote

### ISSUE THREAD

**Issue by skhomutova** [TechnologyMasters/jobs#531]
### Salary Expectation

- Negotiable
- Contract / Full Time

## Your day-to-day responsibilities:
- Develop and maintain Backend solutions using Django
- Collaborating directly with our clients while helping them build great products
- Build docker images that can run on top of AWS or other PaaS
- Model databases using MySQL, Postgres, DynamoDB
- Understand the needs of our partners and come up with solutions for their problems
- Participate in Sprint Plannings and daily stand-up meetings
- Participating in code review and pair programming as a part of your workflow
- Taking an active role in our learning and knowledge sharing culture

## To succeed, you'll likely need the following skills:

- At least 3+ years of professional experience
- Experience with RESTful backend applications, specially built with Django
- Experience with deployment processes like Docker, CircleCI, AWS, Heroku
- Experience with Git
- Experience with different databases
- Knowledge about basic Front-end development
- Knowledge about clean code, design patterns
- Being self-taught
- Being up-to-date with the latest news and technologies about Backend
- English proficiency
- Good communication skills, both in verbal and writing

## About Our company

Apex Labs is a software development studio that builds tech products for US startups.

Our culture is one of remote-first, and our engineering organization is mainly remote. We provide guidance and meet regularly using video calls, and we need people who can work independently and communicate well.

We care deeply about open source, and the projects generally are open source, check them out: https://github.com/apexlabs

Our clients are from various industries like fintech, NFT/crypto, food-tech, aero-tech, and others.

The company is led by devs (the owner is actually coding), so you'll never feel like a cog in the machine. Everyone has the chance to choose the project and make decisions that steer the company as a whole.

If you're an enthusiastic, talented, and resourceful developer with the relevant skills & IT experience, let's talk about creating disruptive products with an international and multidisciplinary team.

## Recruitment Process

- Apply for the job through this form: https://portal.apexlabs.ai/jobs/apply/sr-python-django-engineer-10
- Please note that without seeing the fragment of your code, you will not be considered for the following stages! If you can't show it as a link, please send printscreen to jobs@apexlabs.ai
- Answer a few technical questions during the initial online call
- Welcome aboard!

**Comment by SeniorITNinja** [comment]
Hello, Nice to meet you.
After graduating with my Bachelor’s degree in Computer Science, I’ve spent the last 6+ years building professional experience as a Software Development.
I am very interested in this position because my skillsets match & experience as your company looking for.
my review: Passionate & Responsible developer, Best Colleague.
I’m ready to bring my skills to this developing marketplace. I’ve always dreamed of working at this company, and I was excited to see an opening that’s a perfect fit for my experience and abilities.
Have an extremely software developing, engineering's versatile skill set and I understand the importance of being interactive and enjoy communicating with others for the benefit of the company and
I can be reached anytime by skype(live:.cid.b1a38583392e35b0 ), email ( futuresea.dev@gmail.com ).
I look forward to speaking with you soon.
Sincerely,
