### ISSUE TITLE
Senior Full Stack Engineer - Full Time - MadeFrom

### ISSUE THREAD

**Issue by LeoneBaron** [TechnologyMasters/jobs#536]
We’re hiring at [MadeFrom](www.madefrom.com)! Join our growing team and work with purpose.

Role: Senior Full Stack Engineer
Location: Remote (depending). We have team members in London, Southport and Tallinn - with co-working available in each location.
Details: Flexible start date, ideally ASAP. Unlimited holiday, paid mission days, generous parental leave (including adoption leave). Competitive salary and equity, with a generous learning budget.

We’re accepting rolling applications, and are looking for ‘hit the ground running’ individuals. You’ll have autonomy, support, an enthusiastic team and the chance to make formative contributions to the direction of MadeFrom. See the [job spec](https://madefrom.notion.site/Senior-Full-Stack-Engineer-MadeFrom-c5c0eb2f1986488e87c3973e484542f2) for more detail on our diversity and inclusion principles, and our hiring process.

Learn more about us via our website, and check out cool things we’re building like Low Carbon Business School:
https://www.madefrom.com/careers

**Comment by SeniorITNinja** [comment]
Hello, Nice to meet you.
After graduating with my Bachelor’s degree in Computer Science, I’ve spent the last 6+ years building professional experience as a Software Development.
I am very interested in this position because my skillsets match & experience as your company looking for.
my review: Passionate & Responsible developer, Best Colleague.
I’m ready to bring my skills to this developing marketplace. I’ve always dreamed of working at this company, and I was excited to see an opening that’s a perfect fit for my experience and abilities.
Have an extremely software developing, engineering's versatile skill set and I understand the importance of being interactive and enjoy communicating with others for the benefit of the company and
I can be reached anytime by skype(live:.cid.b1a38583392e35b0 ), email ( futuresea.dev@gmail.com ).
I look forward to speaking with you soon.
Sincerely,
