### ISSUE TITLE
Looking for freelance developer in all tech stacks - remote - all over the globe 

### ISSUE THREAD

**Issue by MeshkaniMohammad** [TechnologyMasters/jobs#608]
[hiring] [freelancers] [remote] [all over the world]
Hey all :wave::skin-tone-2:
We are looking for freelance developers in all technology stacks.
We want to allow you to choose the projects that you would like to work on. We always talk to you as a person, and we do not make a competition on price (like other freelance platforms).
If you would like to work with big brands and have real freedom as a freelancer, submit your CV on this form.

Requirments:
1- At least three years of experience in the industry
2- Good at English communications
3- Experience in freelance jobs and development agencies would be great but unnecessary. 

How do we work?
https://tribes-wiki.super.site/

Who are we?
https://tribes.work

(No agencies, please)
https://hey.campfire.global

**Comment by seitosolano** [comment]
Hi
Thanks for your invitation.
I reviewed your job
[888_seitosolano_resume.pdf](https://github.com/TechnologyMasters/jobs/files/8691861/888_seitosolano_resume.pdf)
 carefully, and I decided to answer you.
I am sure that my experience and skills will be helpful for you to save your time and labour.

I would like to discuss more on an online meeting or phone.
If you are interested in my resume, Please let me know how to start my work with you.
And then I will make an appointment to take an interview with you.

I shared my resume in this email.

Thanks and Regards.

Seito Solano
Freelancer

555 Castro Street Mountain View, Santa Clara CA

Email: seitosolano1982@gmail.com
Phone: (650) 318-5218
SkypeID: live:.cid.bfbf2f881a5e64a7

**Comment by smart0815** [comment]
Hello, thanks for your job posting
I'd like to discuss your project in more detail
I'm ready to share my experience via interview

I hope you're doing well
Best regards

Email: [jonnel0617@gmail.com](mailto:jonnel0617@gmail.com)
SkypeID: live:.cid.99c8edd01ac0cb2b

**Comment by seitosolano** [comment]
Hello, thanks for your careful invitation.
As a senior full stack developer, I always expect to have a exciting moment that I can contribute in your work by my practical skills and experience.
I'm ready to discuss more on online meeting like google or zoom.
Best regards.

**Comment by seitosolano** [comment]
Hi, Jackson.
Thanks for your invitation.
I hope to devote my skills and experience to your work, because I am sure that my skills and experience would be helpful for you to save the time and the labour.
I think that what is more important is skills and experience than any wealth.

I will wait for your reply.
Anytime okay, It would be better if you call upon me on online meeting like google or zoom

Best Regards.
Seito Solano.

**Comment by seitosolano** [comment]
Hi, Jackson, Sorry for bothering you.
Something for your work figured out of mind, so that I dropped my notes again.

I would like to inquire a few of question.

•	is it on-going project or startup project?
•	do you have wireframe, layout design or meta, API requirement, database structure
preparation for integrating the 3rd party service like google, firebase or AWS
practical issue measurement such as estimation of payload on your service, such as responding time, concurrent access 
•	do you have a roadmap of your project

I would like to discuss more one by one about your project with your teams
I get used to take a discussion on online meeting like zoom or google.
Seito Solano
Regards.
